export type PortfolioEntry = { title: string; subtitle?: string; date?: string; text?: string; bullets?: string[]; tags?: string[]; href?: string; status?: 'Submitted' | 'Published'; authors?: string; grade?: string };
export type PortfolioSection = { title: string; eyebrow: string; intro: string; entries: PortfolioEntry[] };
export const profile = {
 name: 'Aditya Gupta', role: 'Polymer Materials Researcher', email: 'aditya_g@pt.iitr.ac.in', cv: '/aditya-gupta-resume.docx',
 summary: 'I am a polymer materials researcher with an M.Tech. in Packaging Technology from IIT Roorkee. My work spans biodegradable polymer blends, electrospun fibres, cellulose composites and functional packaging.',
 approach: 'My work connects extraction, formulation, and processing with material performance, using structural, thermal, mechanical, and electrochemical characterization.',
 interests: ['PHA- and PLA-based materials','Cellulose-reinforced biocomposites','Crystallization and thermal behaviour','Sustainable polymer processing','Circular materials','Biodegradable plastics'],
 socials: [{title:'Email',label:'aditya_g@pt.iitr.ac.in',href:'mailto:aditya_g@pt.iitr.ac.in',description:'For research opportunities and collaboration.'},{title:'LinkedIn',label:'Connect professionally',href:'https://www.linkedin.com/in/aditya-gupta-554a04212',description:'Academic experience and professional connections.'},{title:'ORCID',label:'0009-0004-6813-810X',href:'https://orcid.org/0009-0004-6813-810X',description:'My persistent researcher identifier.'},{title:'Google Scholar',label:'Explore my scholar profile',href:'https://scholar.google.com/citations?user=aqpP2owAAAAJ&hl=en',description:'My research profile and scholarly work.'},{title:'ResearchGate',label:'Research profile',href:'https://www.researchgate.net/profile/Aditya-Gupta-199?ev=hdr_xprf',description:'Publications and research connections.'}],
};
export const sections:Record<string,PortfolioSection>={
 about:{title:'About Aditya.',eyebrow:'ABOUT / RESEARCH SUMMARY',intro:'Polymer materials researcher · M.Tech., IIT Roorkee · Visiting Researcher, University of Nizwa.',entries:[{title:'From formulation to function',text:profile.summary},{title:'A connected view of materials',text:profile.approach},{title:'Research interests',tags:profile.interests}]},
 education:{title:'A foundation in materials.',eyebrow:'EDUCATION / ACADEMIC JOURNEY',intro:'From textile structures to advanced packaging materials—a learning journey grounded in engineering.',entries:[{title:'M.Tech. · Packaging Technology',subtitle:'Indian Institute of Technology, Roorkee',date:'2025',grade:'8.737 CGPA'},{title:'B.Tech.',subtitle:'Indian Institute of Carpet Technology',date:'2023',grade:'6.900 CGPA'},{title:'Intermediate · Class XII',subtitle:'Central Academy',date:'2018',grade:'63.40%'},{title:'Matriculate · Class X',subtitle:'Saraswati Shishu Mandir Sr. Sec. School',date:'2016',grade:'8.400 CGPA'}]},
 experience:{title:'Research, in practice.',eyebrow:'EXPERIENCE / CURRENT RESEARCH',intro:'Developing functional, active, and sustainable packaging systems for food protection and shelf-life extension.',entries:[{title:'Visiting Researcher',subtitle:'Natural and Medical Sciences Research Centre · University of Nizwa, Oman',date:'October 2025 – Present',bullets:['Designed and fabricated biodegradable polymer films and electrospun fibre systems based on PCL/gelatin, gelatin/sodium alginate, gelatin/methyl cellulose, PLA/cellulose, PVA, PHA, and PLA composites.','Optimized polymer concentration, blend ratio, viscosity, surfactant concentration, and electrospinning parameters to control fibre formation, bead defects, and morphology.','Developed PCL/gelatin bilayer microfibres and gelatin-based nanofibres containing MOF, ZnO, and MgO-loaded active-agent nanoparticles.','Synthesized Zn-, Cu-, and Fe-fumarate coordination materials and investigated their incorporation into biopolymer composites.','Evaluated relationships between formulation, morphology, crystallinity, thermal stability, mechanical performance, surface properties, and barrier behaviour.','Contributed to experimental design, data interpretation, manuscript preparation, and collaborative characterization.'],tags:['Biopolymer films','Electrospinning','Active packaging','Coordination materials']}]},
 publications:{title:'Publications.',eyebrow:'PUBLICATIONS / SCHOLARLY WORK',intro:'Research on responsive sensors, multilayer biopolymer films, and active packaging materials.',entries:[{title:'Radio Frequency Identification Enabled Hydrogel Sensor for Real Time Oxygen Sensing In Smart Food Packaging',authors:'Aditya Gupta, Kirtiraj K. Gaikwad',date:'2026',subtitle:'Packaging Technology and Science',status:'Submitted'},{title:'Multilayer Biopolymer-Based Flexible Packaging Films Via Layer-By-Layer Assembly: A Comprehensive Review',authors:'Aditya Gupta, Kirtiraj K. Gaikwad',date:'2026',subtitle:'Polymer International',status:'Published',href:'https://doi.org/10.1002/pi.70114'},{title:'Recovery of Bioactive Polyphenolic Components from Rhazya stricta Waste into Ursolic Acid-Enriched Biocomposite Films for Sustainable Food Packaging Applications',authors:'Talha Shireen Khan, Aditya Gupta, Ahmed Al-Harrasi, Najeeb Ur Rehman, Saurabh Bhatia',date:'2026',subtitle:'Journal of Packaging Technology and Research',status:'Published',href:'https://doi.org/10.1007/s41783-026-00205-z'},{title:'Comparative Study on Molecular Docking of Chitosan-Based Thin Films Enriched with Commiphora Mukul and Commiphora Kua Resins as an Active Packaging Materials',authors:'Yasir, Abbas Khan, Aditya Gupta, Saurabh Bhatia',date:'2026',subtitle:'Chemistry Select',status:'Published',href:'https://doi.org/10.1002/slct.72834'},{title:'Impact of Different Surfactants on Chitosan/Sodium Alginate Films Reinforced with Bergamot Oil',authors:'Aditya Gupta, Saurabh Bhatia',date:'2026',subtitle:'Polímeros',status:'Published',href:'https://doi.org/10.1590/0104-1428.20250121'}]},
 projects:{title:'Selected research.',eyebrow:'PROJECTS / SELECTED WORK',intro:'Investigating smart sensing, layered materials, and the geometry of engineered structures.',entries:[{title:'RFID-integrated conductive hydrogel for oxygen detection',subtitle:'Indian Institute of Technology, Roorkee',date:'July 2024 – May 2025',text:'Development of a smart packaging system using a PVA-based conductive hydrogel as an oxygen-sensitive material.',bullets:['Integrated the hydrogel with RFID technology for wireless, non-invasive monitoring.','Target applications include food safety, pharmaceuticals, and perishable-goods logistics.'],tags:['PVA hydrogel','RFID','Oxygen sensing','Smart packaging']},{title:'Multilayer biopolymer-based flexible films',subtitle:'Indian Institute of Technology, Roorkee',date:'July 2024 – May 2025',text:'Exploration of the layer-by-layer (LBL) technique for flexible films with customizable properties.',bullets:['Used LBL assembly to tailor film designs to specific functional requirements.','Investigated multilayer structures for improved mechanical properties and durability.'],tags:['Layer-by-layer assembly','Biopolymers','Flexible films']},{title:'Mathematical designs in carpet manufacturing',subtitle:'Indian Institute of Carpet Technology',date:'August 2022 – June 2023',text:'Applied fractal geometry and mathematical patterns to carpet design.',bullets:['Developed complex patterns and explored mathematical principles for carpet aesthetics.','Considered manufacturing feasibility for both hand-made and machine-made tufted carpets.'],tags:['Fractal geometry','Textile design','Manufacturing']}]},
 internships:{title:'Learning on the production floor.',eyebrow:'INTERNSHIPS / INDUSTRIAL EXPOSURE',intro:'Connecting classroom knowledge with textile processing and manufacturing practice.',entries:[{title:'Internship Training',subtitle:'Raymond Luxury Cottons Limited',date:'July 2022',text:'Industrial training across linen and cotton processing.',bullets:['Linen spinning line.','Weaving of cotton and linen.','Pretreatment and processing of linen fibre.']}]},
 achievements:{title:'Beyond the laboratory.',eyebrow:'ACHIEVEMENTS / TEAMWORK',intro:'A sporting achievement from my time at IIT Roorkee.',entries:[{title:'Second Place · Football',subtitle:'SHAURYA Tournament · IIT Roorkee',date:'2023',}]},
 skills:{title:'Tools for asking better questions.',eyebrow:'SKILLS / METHODS & CAPABILITIES',intro:'A multidisciplinary toolkit for processing, characterizing, and interpreting polymer materials.',entries:[{title:'Polymer processing',tags:['Electrospinning','Solution casting','Extrusion molding and casting','Layer-by-layer assembly','Hydrogel synthesis','Polymer extraction from waste','Polymer blending','Nanocomposites','MOF synthesis']},{title:'Characterization',tags:['SEM','TEM','AFM','XRD','TGA / DSC','FTIR','WVTR / OTR','DLS','Mechanical testing','UV-visible spectroscopy','Water contact angle','Electrochemical impedance spectroscopy','Biodegradation analysis']},{title:'Programming',tags:['C++','Python']},{title:'Software',tags:['Visual Studio Code','Microsoft Word','Microsoft PowerPoint','Microsoft Excel','Adobe Photoshop','CorelDRAW','OriginPro','Canva']},{title:'Additional courses & certifications',bullets:['Patent Law for Engineers and Scientists · NPTEL','Google Data Analytics Professional Certificate · Coursera','Google UX Design Professional Certificate · Coursera']},{title:'Languages',tags:['English','Hindi']}]},
 leadership:{title:'Contributing beyond my research.',eyebrow:'LEADERSHIP / COMMUNITY & PARTICIPATION',intro:'Supporting student communities through coordination, communication, and professional development.',entries:[{title:'General Secretary',subtitle:'Indian Institute of Carpet Technology',date:'July 2022 – May 2023',bullets:['Coordinated the other secretaries to support smooth campus activities.','Provided information and helped students explore opportunities and allied activities.']},{title:'Editor · TANA BANA Magazine',subtitle:'Indian Institute of Carpet Technology',date:'August 2022 – May 2023',text:'Edited the institute’s annual magazine.'},{title:'Department Placement Representative for Internship',subtitle:'Packaging Technology · Indian Institute of Technology, Roorkee',date:'August 2023 – November 2025',bullets:['Supported departmental placement and internship activities.','Provided information and helped students prepare for training and allied activities.']},{title:'Visitor · PackPlus',subtitle:'Packaging, converting, and supply-chain event',date:'August 2024',}]},
 references:{title:'Academic reference.',eyebrow:'REFERENCES / RESEARCH MENTORSHIP',intro:'An academic reference from my work at IIT Roorkee.',entries:[{title:'Prof. Dr. Kirtiraj K. Gaikwad',subtitle:'HOD and Associate Professor',text:'Department of Paper Technology · Indian Institute of Technology, Roorkee',bullets:['Contact details are included in my downloadable résumé.']}]},
 contact:{title:'Let’s connect.',eyebrow:'CONTACT / RESEARCH CONNECTIONS',intro:'For academic opportunities and collaborations in sustainable and smart packaging.',entries:[]},
};
export const pageLabels:Record<string,string>={about:'About',education:'Education',experience:'Experience',publications:'Publications',projects:'Projects',internships:'Internships',achievements:'Achievements',skills:'Skills',leadership:'Leadership',references:'References',contact:'Contact'};

export const materials = [
  { id: 'film', title: 'Flexible films.', image: '/flexible-film.jpg', alt: 'Illustrative natural study of a thin, translucent flexible biopolymer film', description: 'Formulating biodegradable polymer films and layered structures for functional packaging.', label: 'BIOPOLYMERS / FLEXIBLE PACKAGING' },
  { id: 'fibres', title: 'Electrospun fibres.', image: '/nanofibre-mat.jpg', alt: 'Illustrative close-up of a softly folded, porous nanofibre mat', description: 'Tuning polymer blends and electrospinning conditions to shape fibre formation and morphology.', label: 'ELECTROSPINNING / FIBRE MATS' },
  { id: 'straws', title: 'Edible materials.', image: '/edible-straws.jpg', alt: 'Illustrative natural study of three matte, hollow edible straws', description: 'Exploring edible straws and material alternatives for everyday use.', label: 'EDIBLE STRAWS / MATERIAL ALTERNATIVES' },
] as const;
export const routeDescriptions: Record<string, string> = {
  about: 'Aditya Gupta’s research experience, education, methods, leadership and academic background in polymer materials and packaging.',
  projects: 'Research projects in RFID hydrogel sensing, multilayer biopolymer films and mathematical textile design by Aditya Gupta.',
  publications: 'Publications and submitted research by Aditya Gupta, with authors, journals and DOI links.',
  contact: 'Contact Aditya Gupta for academic opportunities and research collaborations in sustainable and smart packaging.',
};
